---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-policy-controller
  template:
    metadata:
      labels:
        name: config-policy-controller
    spec:
      serviceAccountName: config-policy-controller
      containers:
        - image: quay.io/open-cluster-management/config-policy-controller:latest
          name: config-policy-controller
          command:
          - config-policy-controller
          args:
            - "--enable-lease=true"
            - "--hubconfig-secret-name=hub-kubeconfig"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "config-policy-controller"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-policy-controller
subjects:
- kind: ServiceAccount
  name: config-policy-controller
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: config-policy-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-policy-controller
