---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-policy-controller-auth
subjects:
- kind: ServiceAccount
  name: config-policy-controller
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: config-policy-controller-auth
  apiGroup: rbac.authorization.k8s.io
