name: Framework

on:
  push:
    branches:
      - main
      - release-[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+

jobs:
  fw-kind-tests:
    name: KinD
    uses: stolostron/governance-policy-framework/.github/workflows/kind.yml@main
